### ISSUE TITLE
ERROR(1052): Invalid element

### ISSUE THREAD

**Issue by woodhawk109** [ShikyoKira/Project-New-Reign---Nemesis-Main#127]
Hi, I just updated to the latest nemesis version and try to launch the animation system and I got the following error:

ERROR(1052): Invalid element. Only empty, "F", "L" or digit is acceptable as input element. Please contact the template creator
Template: s
File: #0200
Line: 23
Option: 					<hkparam name="eventId">$eventID[s[F][main_anim_event]]$</hkparam>

The version is :
Checking engine version
Engine is up to date
Version Code: 2445-2708

**Comment by ShikyoKira** [comment]
upload your patchlog,txt

**Comment by marcospdsf** [comment]
Well... Since he is not going to upload then I would like to take advantage, if you would like to help me... Here is my PatchLog. It could point wich mod is giving the error so we could delete or change it... 
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4389455/PatchLog.txt)

**Comment by marcospdsf** [comment]
So... Digging up the way of the log... I figured out that the last tried folder with animations is the one giving problems... Wich for me, was pretty much all sexLab animations that I had... Saddly I had to remove all to work...

**Comment by ShikyoKira** [comment]
fixed in v0.84 onwards
