### ISSUE TITLE
Crash after game launch

### ISSUE THREAD

**Issue by FlyDut** [ShikyoKira/Project-New-Reign---Nemesis-Main#141]
Hello, I used the nemesis engine according to the instructions, but when I ran the game through mo2, the game crashed. How can I solve this problem?

**Comment by boycad** [comment]
Hello to you too, Sir. I'm absolutely not a professional in my knowledge of this tool, but your post has a obvious deficiency I can point out. Modded games crash on launch quite frequently. Please explain why you think it is because of Nemesis that your game crashed here.                                                                                                                                                                                                                 From: FlyDutSent: Tuesday, February 4, 2020 1:38 PMTo: ShikyoKira/Project-New-Reign---Nemesis-MainReply To: ShikyoKira/Project-New-Reign---Nemesis-MainCc: SubscribedSubject: [ShikyoKira/Project-New-Reign---Nemesis-Main] Crash after game launch (#141)Hello, I used the nemesis engine according to the instructions, but when I ran the game through mo2, the game crashed. How can I solve this problem?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/issues/141?email_source=notifications\u0026email_token=ADESXKLE3JTH2BSWAJPQFYDRBHN53A5CNFSM4KP6M5QKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ILA2UYA",
"url": "https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/issues/141?email_source=notifications\u0026email_token=ADESXKLE3JTH2BSWAJPQFYDRBHN53A5CNFSM4KP6M5QKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ILA2UYA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by FlyDut** [comment]
> Hello to you too, Sir. I'm absolutely not a professional in my knowledge of this tool, but your post has a obvious deficiency I can point out. Modded games crash on launch quite frequently. Please explain why you think it is because of Nemesis that your game crashed here. From: FlyDutSent: Tuesday, February 4, 2020 1:38 PMTo: ShikyoKira/Project-New-Reign---Nemesis-MainReply To: ShikyoKira/Project-New-Reign---Nemesis-MainCc: SubscribedSubject: [ShikyoKira/Project-New-Reign---Nemesis-Main] Crash after game launch (#141)Hello, I used the nemesis engine according to the instructions, but when I ran the game through mo2, the game crashed. How can I solve this problem? —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#141?email_source=notifications\u0026email_token=ADESXKLE3JTH2BSWAJPQFYDRBHN53A5CNFSM4KP6M5QKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ILA2UYA", "url": "#141?email_source=notifications\u0026email_token=ADESXKLE3JTH2BSWAJPQFYDRBHN53A5CNFSM4KP6M5QKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ILA2UYA", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]



> Hello to you too, Sir. I'm absolutely not a professional in my knowledge of this tool, but your post has a obvious deficiency I can point out. Modded games crash on launch quite frequently. Please explain why you think it is because of Nemesis that your game crashed here. From: FlyDutSent: Tuesday, February 4, 2020 1:38 PMTo: ShikyoKira/Project-New-Reign---Nemesis-MainReply To: ShikyoKira/Project-New-Reign---Nemesis-MainCc: SubscribedSubject: [ShikyoKira/Project-New-Reign---Nemesis-Main] Crash after game launch (#141)Hello, I used the nemesis engine according to the instructions, but when I ran the game through mo2, the game crashed. How can I solve this problem? —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#141?email_source=notifications\u0026email_token=ADESXKLE3JTH2BSWAJPQFYDRBHN53A5CNFSM4KP6M5QKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ILA2UYA", "url": "#141?email_source=notifications\u0026email_token=ADESXKLE3JTH2BSWAJPQFYDRBHN53A5CNFSM4KP6M5QKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ILA2UYA", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Thank you for your reply, because when I use fnis, the game can start normally. I think there is an error in the nemesis engine, or there is a conflict with other modules. I really like ultimate dodge and I hope to be able to use it. But I don't know what kind of information to provide. I want to know what log reports should be provided?

**Comment by ShikyoKira** [comment]
you should start by doing some testing on your own to narrow down the possible cause. First off, start by using Nemesis only without any mod. If it doesn't crash, then it is not "Nemesis crash your game". It is possible for it to be mod conflict or so

Do you have Halo Poser installed by any chance? If so, then yea.. thats the one. Currently fixing it

**Comment by FlyDut** [comment]
> you should start by doing some testing on your own to narrow down the possible cause. First off, start by using Nemesis only without any mod. If it doesn't crash, then it is not "Nemesis crash your game". It is possible for it to be mod conflict or so
> 
> Do you have Halo Poser installed by any chance? If so, then yea.. thats the one and i'll close this issue for duplicating report. Currently fixing it anyway

( I don't know English very well. I hope machine translation won't affect your reading.)
I tested again and found that I should have three wrong sources.

I uninstalled MO2 completely and reinstalled it. When Skyrim SE was started, the error did not reappear (I'm sorry I didn't write down the version number, I have forgotten what version...).

But in Skyrim LE, errors still exist. I checked the plug-in of skse and found that the error came from hdt-smp，because I have OpenCL enabled.

After that, I found that when the Nemesis Engine used more than a certain number of animations (the range should be 15000 to 17000), the game started and crashed.

Fortunately, now I just need to reduce the animation properly, and the game will run normally. In any case，thank you very much for your work.

**Comment by FlyDut** [comment]
> you should start by doing some testing on your own to narrow down the possible cause. First off, start by using Nemesis only without any mod. If it doesn't crash, then it is not "Nemesis crash your game". It is possible for it to be mod conflict or so
> 
> Do you have Halo Poser installed by any chance? If so, then yea.. thats the one and i'll close this issue for duplicating report. Currently fixing it anyway

I'm sorry to disturb you again. Because my side is the eastern time zone, so I slept for a day. I'm going to do some further testing after I go to sleep to confirm the specific version of HDT SMP. It should be noted that after using a clean environment, I can't reproduce the errors of HDT SMP, no matter what version of HDT SMP is, or Skyrim LE and Skyrim SE.
At present, this may not be caused by the nemesis engine.

When mo2 uses version 2.2.0, there will be problems. I've seen some feedback before, and I'm glad that this problem has been solved in the new version.

Thank you again for your efforts

**Comment by ShikyoKira** [comment]
thank you for your update. I'll close this issue for now until there is further appearance of this issue in current or newer version
