### ISSUE TITLE
Nemesis and XPMSE

### ISSUE THREAD

**Issue by nyriahx3** [ShikyoKira/Project-New-Reign---Nemesis-Main#154]
please help me I tried everything reinstalled anything my papyrus is full of these everytime i crash
https://pastebin.com/vw52H3wk
https://pastebin.com/LjGTNxd0
it feels like iam mostly crashing when entering a new exterior cell (random crashes while running through tamriel)

nemesis log
https://prnt.sc/r4z1wp

**Comment by nyriahx3** [comment]
Iam also having issues with the skee64.dll that is a hardrequirement for some mods I use, disabling the dll is helping( less ctd)
I already installed the MCM Version of xpmse instead of the racemenu version, iam running out of ideas

**Comment by ShikyoKira** [comment]
please update your nemesis. `bIsNemesisLocked` has been fixed some time ago

**Comment by nyriahx3** [comment]
bIsNemesisisLocked is gone now but everytime I crash this is at the end now:
https://pastebin.com/6JhzJwcd
It feels like its crashing cause of the bodycleanup or this cannot fetch error, idk I already reinstalled everything

**Comment by ShikyoKira** [comment]
to be honest, i don't think this will cause crash. This is just a warning message. not a crash report anyway. My papyrus can have tonnes of this but not crash =/

Still i'll fix this annoying messages in upcoming version. As for the crash, you really should look at somewhere else. This is not the cause. How about start by removing XPMSE, see if it fixes it since it should stop the papyrus from spamming that message

**Comment by ShikyoKira** [comment]
No update on this matter for more than a month. Closed. Open if there is more
