### ISSUE TITLE
New engine update. idp.alexa.51?

### ISSUE THREAD

**Issue by JhonAkira** [ShikyoKira/Project-New-Reign---Nemesis-Main#161]
Hi,

First of all, I would like to thank you for this animation mod engine you created and I'm currently using it on my game. I'm really enjoying it and its like a breath of fresh air. One thing that bothers me is due to the new engine update, my antivirus is suddenly detecting this as idp.alexa.51. I just want to give you a heads up and I do hope that you can shed light on this.

**Comment by ShikyoKira** [comment]
ok, this is a false alarm i have to say. I kinda expects that because while updating, Nemesis scans through a ton of Nemesis files and write a ton of stuffs too. So for an antivirus, this kind of behavior is suspicious indeed and an obvious indication of a potential virus

This is something we can't fix without significantly changing the current structure and potentially remove many features and flexibility for modders. So the only reasonable way to fix it is to white list it

**Comment by JhonAkira** [comment]
I see, yeah it kinda happened after i updated the engine. After that, I ran the generate behaviour and while running, my antivirus said it detected idp.alexa.51. I scanned the exe with both avast and malwarebytes and they both say the exe is clean. Only during the generate behaviour did I get a detection.

**Comment by JhonAkira** [comment]
I have one question though. Do I need to uninstall fnis to install nemesis correctly? I tried them both in the same load order. I kinda left them both active and I was wondering if it will cause some conflict.

**Comment by ShikyoKira** [comment]
you have to remove fnis. Using both will definitely cause conflict

**Comment by JhonAkira** [comment]
I see. Thanks for the reply.
