### ISSUE TITLE
install error 6010

### ISSUE THREAD

**Issue by atrolle224** [ShikyoKira/Project-New-Reign---Nemesis-Main#163]
Howdy tried to install nemesis but encountered an error  
"ERROR(6010): Detected path does not match expected installation path. Please reinstall Nemesis correctly
Detected path: X:\Skyrim\data\Nemesis_Engine
Expected path: C:\Program Files (x86)\Steam\steamapps\common\Skyrim\Data\nemesis_engine"

I play Skyrim on a separate drive, not my c drive; is it possible for you to fix this? Or can I only use this is I have Skyrim installed on my c drive?

**Comment by ShikyoKira** [comment]
open `nemesis.ini` located in `data\nemesis_engine\`. Edit the `SkyrimDataDirectory` to your designated path

**Comment by WStegem** [comment]
Nemesis still checks if there is a Skyrim folder in the default location, regardless of the ini. I have a clean Skyrim installation in my Steam folder and pointed Nemesis to the real folder I was using, but Nemesis wouldn't install, because it detected the clean one and reset the expected location. It would then give me an error, saying that the detected path wasn't expected.
