### ISSUE TITLE
XP32 Maximum Skeleton problem!

### ISSUE THREAD

**Issue by oguba** [ShikyoKira/Project-New-Reign---Nemesis-Main#165]
When XP32 is enabled, Nemesis gets stuck at %100. Is XP32 not supported?

**Comment by ShikyoKira** [comment]
It is supported. It getting stuck at 100% or not vary machine from machine. Most machines won't. But unfortunately yours does, however, I have changed how the underlying threading method works. I should be more stable in the following update

**Comment by oguba** [comment]
Ok, thank you. How long does it usually take for a new update come out? I just started using Nemesis recenty, so I'm not familiar with the schedule.

**Comment by ShikyoKira** [comment]
in a month or 2. Last update was jan. So you should expect it coming out soon. Sometimes up to 4 months. Depending on how much the changes we have for that update. A lot of times is just we want to add a specific feature, while adding it, we have a tonnes of minor changes due to report coming in. So these minor fixes can take up a lot of time making ruining the schedule
