### ISSUE TITLE
Animations for throwing weapons lite don't work

### ISSUE THREAD

**Issue by reza9892** [ShikyoKira/Project-New-Reign---Nemesis-Main#166]
Hi, 
well my isssue is exactly what the title states, animations for the mod throwing weapons lite by jzbai don't work with nemesis.
Thanks for the new engine, I understand it opens many new doors for modifying behaviours and I'm very excited for the full release.

**Comment by ShikyoKira** [comment]
hi, do you mean first person? I tried 3rd person its working fine for me

**Comment by reza9892** [comment]
Thanks for the quick response, no the 3rd person ones don't work for me

**Comment by ShikyoKira** [comment]
lets ignore the 1st person for now. I know it doesn't work because i tried it. And this problem is on the mod author's side not me. We will just focus on the 3rd person for now. 

Have you tried it with a very bare load order? As little mod as possible. Best if you can have it with just Nemesis, Throwing weapon lites, SKSE, alternate life and some really essential mods

**Comment by reza9892** [comment]
well now I feel dumb it works

**Comment by reza9892** [comment]
but it doesn't when with other animation mods, trying to pinpoint which one is incompatible

**Comment by reza9892** [comment]
shit, it's xpmse

**Comment by ShikyoKira** [comment]
ok i suspect this might a duplicated issue of #134 , it has been fixed in unreleased version, which will be out soon
