### ISSUE TITLE
FNIS Sexy Move is playing the wrong animations

### ISSUE THREAD

**Issue by ShikiRyugi** [ShikyoKira/Project-New-Reign---Nemesis-Main#167]
Hi,
for me at least Sexy Move is working. The MCM is showing, I can change the animations for the PC and disallow some for the female NPCs. FNIS Sexy Move is even playing a different animation for each sexy move.
BUT the animations are not sexy movements, but rather bound animations! All female NPC move as if they are bound by something and for several animations as if they have movement restricting boots on.

This ONLY is the case for all Sexy Moves. For the PC you can also choose the default movement which is working normally / lets the PC at leas walk with the general installed female walk animation. 

Starting a new game or rearranging the load order of the FNIS Sexy Move esp file did not help.

The FNIS esp file is installed. I have first run FNIS and later Nemesis (out of necessity).
I am using CBE.
My animation adding mods are all in one big merge.

My guess is that Nemesis is handling FNIS Sexy move correctly (otherwise the MCM + the changing movement animations would not work), but it either has problems with my animations merge, so other mod form LoversLab,     or maybe it is the combination with CBE that overwrites many behaviour files (also some of FNIS) and rearranges the references.

**Comment by ShikyoKira** [comment]
duplicated issue of #134

**Comment by badbonez** [comment]
I am having this same issue - and I do not think it is the same as [134](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/issues/134 ).  Because in that issue it's animations within Devious Devices that are not playing correctly, while my issue is that when I run Nemesis with Devious Devices installed, the FNIS animations play the Devious Devices issue.  And while issue 134 says you created a commit to that error, I am still experiencing this.  The only way to prevent this is to not include Devious Devices when I launch the Nemesis engine.  Or run FNIS at the same time.

**Comment by ShikyoKira** [comment]
Why do i say its the same is not because of the mod but the based mechanics. Both are resulted from the same bugged mechanics, which ultimately result in playing wrong animation
