### ISSUE TITLE
FNIS + Nemesis (SLab)

### ISSUE THREAD

**Issue by Chazito** [ShikyoKira/Project-New-Reign---Nemesis-Main#262]
I recently updated Nemesis and my animations died. I had FNIS and Nemesis installed with over 16K animations. I used FNIS to build SLab anims, then I disabled FNIS in MO2 and proceeded to build CO + 360 Movement on Nemesis, that worked for me and I didn't had any crashes or problems. Now my animations are weird, only creatures are working correctly and humans don't.
Building animations only on FNIS or Nemesis makes them work but they have their loses:
- Building on FNIS leaves me without Combat Overhaul and 360 Movement
- Building on Nemesis leaves me with an animation limit of about 13-14K.

I would like to know of any tips or fixes before someone gives me the "use less mods".

**Comment by ShikyoKira** [comment]
Because they don't work together, both are doing the same thing, both are not compatible to each other. You are free mess with it but sorry, don't expect I fix something you have broken from your mix and match

Please note that you are using a beta tool. So don't expect it to be perfect atm. For now, you have to pick either this or that. Until in later version, only will we get a better and more stable tool

My hands are already full dealing with all the issues and programming, so don't ask me to fix your problem unless the problem is from Nemesis alone

And sorry, there is no magic in programming, use less animation is the only solution you have now other than waiting for next version that has a fix to it
