### ISSUE TITLE
Setup automatic builds for nemesis

### ISSUE THREAD

**Issue by ExtReMLapin** [ShikyoKira/Project-New-Reign---Nemesis-Main#263]
Automatic build would be nice, as the last release is 5 months old

**Comment by ShikyoKira** [comment]
define automatic build

**Comment by ExtReMLapin** [comment]
On each commit or on each branch merge, a build is generated and the exe/zip is pushed [here](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/releases)

The idea is to prevent you or us from having to manually build it.

**Comment by ShikyoKira** [comment]
branch merge is possible, as a lot of times i just commit after finishing a feature, and that feature doesn't guarantee the overall functionality. I understand your concern here

the modus operandi for me before each release is test extensively as you know changing 1 thing often breaks another in programming, it is the same here. And also because Bethesda...

fortunately, i have a team of beta testers to do that. The public releases often have gone through beta phase except if its just a minor tweak or quick fix

Here i have some responsibility to myself and my beta tester team. To reduce the number of issues filed, so to not overwhelm me and burden my team as we don't have time to do free tech support (you know how many people don't read or do their own research before they come to you) and i can't afford to have me and my beta testers exhausted from just helping people fixing their problem and testing each releases

Sometimes I have to discuss with mod authors what's best for them and how to handle their compatibility issues, that take times too

The procedure we have here atm is to protect our sanity and keep us motivated, and also since I'm the only developer here. To reduce number of times we are required to test and number of reports. If we can solve this, certainly we can shorten the release date for each update

As for new release, it will be out soon, it is in currently being tested by some testers
