### ISSUE TITLE
Error 6001 during engine update, maybe unicode problem?

### ISSUE THREAD

**Issue by laymn** [ShikyoKira/Project-New-Reign---Nemesis-Main#275]
I got error 6001 during engine update with Nemesis engine 0.84

During searching for the reason, I found something.
If there is a folder or file name written in non-latin characters within skyrim data folder, Nemesis do error 6001 during engine update.

In MO2, I activated only one mod, as mentioned above, then, run nemesis. I got error.
I changed folder (it is redundant temporary folder) name to non-latin to latin characters.
Then nemesis ran engine update without error.

But, I got another error with ZAZ animation pack. because for now, I can not find any non-latin characters in folder or file name.

**Comment by laymn** [comment]
I finally found it. ZAZ animation pack had a file include 'ö'

**Comment by woodhawk109** [comment]
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4699519/UpdateLog.txt)

I'm getting this as well. I'll wait for a hotfix since there are a lot of folders in my Skyrim/data directories and it'll be pretty difficult to go through them all to find the files with non-latin characters.

I should also mention that occasionally when trying to update, instead of the Error 6001, the engine just hard crash with a blank Critical Error message. When that happens, I'll have to use Window Task Manager to close the program

**Comment by ShikyoKira** [comment]
separate issue please open new issue. Don't lump everything in 1. Please read the description in [main page](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main) before you post any issue for I will ignore and close any issue that does not fit the criteria stated there as I don't have time to help everyone who do not wish to cooperate, not saying you are just dropping a gentle reminder here. Thanks for reporting

This is a duplicated issue of #273 and actively being looked at
