### ISSUE TITLE
Error Code: 5020 for animationsetdatasinglefile.txt

### ISSUE THREAD

**Issue by RawFear101** [ShikyoKira/Project-New-Reign---Nemesis-Main#281]
I've been having trouble for two months with the engine. I think the animationsetdatasingle.txt file is in the incorrect format or there's an error with one of the lines. The engine closes within 2 seconds after flashing this message, so I cannot copy and paste. I've tried reinstalling everything with Nemesis, and I have not found a solution. I refuse to reinstall skyrim for the fear of losing all of the mod work I've done to make this game stunning. Any suggestions?

**Comment by RawFear101** [comment]
ERROR(5005): BUG FOUND!! Report to Nemesis' author immediately
File: temp_behaviors\animationsetdatasinglefile.txt
Line: 91695

Failed to generate behavior

The above is what I was getting prior to v0.84, then once I downloaded and installed v0.4, I began getting error code 5020.

**Comment by ShikyoKira** [comment]
Only post issue you face in the latest version. We don't go back in time to fix the problem in the early version

If you don't want to lose the work you have done for your skyrim, then create a separate profile for testing this. Please be reminded that this is a beta tool. You are using something still underdevelopment, whatever kind of bug is possible including screwing some files here and there

Read the description in the main page of this repository before you open an issue. You aren't providing sufficient information in order for me to replicate this issue. 

I will not proceed with this issue until we have more information atm due to the near impossibility of fixing it with what I have now. Thanks

**Comment by RawFear101** [comment]
My apologies. I am just frustrated that I've not been able to figure out a solution quickly. 

I'll work on getting the information to you as quickly as possible, If I find a solution I'll let you know how I got there.

**Comment by RawFear101** [comment]
Hello Shikyora, 

Nemesis works perfectly on a new Skyrim SE profile. So there is something wrong with my modded skyrim SE profile. I will try to see what is causing this on my end. 

Thank you for the quick responses!

**Comment by RawFear101** [comment]
Update: I was able to get the engine working on my modded skyrim profile by copy and pasting all files from the newly installed profile. I will do m0ore testing tomorrow with animations, but I think we can safely close this issue as the errors are now gone. The errors seemed to have came from manipulated SSE core files.

**Comment by ShikyoKira** [comment]
Thanks for the update and being responsible for doing extensive test as users should. I'll close this issue now

**Comment by XEntity171** [comment]
I have the same issue can u pls help me fix this cause I have no idea how to myself
