### ISSUE TITLE
Nemesis|CGO Dodge Animation

### ISSUE THREAD

**Issue by toudei** [ShikyoKira/Project-New-Reign---Nemesis-Main#290]
Hey, first of all thanks for this great mode, 
But I have a little bug here, I made everything work, except for dodging. Firstly when I dodged as a female, I had an animation in 3rd person.
Then I found on some thread that I need to replace the txt that ShikyoKira send in engine folder.
Right now I dont have animation in 3rd person nor for male nor for female.
Haven't been able to find a solution in previous threads, sorry if repeating.

**Comment by ShikyoKira** [comment]
Too confusing. kindly read it in a clear way describing your issue and make sure the issue is following the guidelines stated in the main page of this repo within 5 days or else it will be closed

**Comment by SH3R4TA5** [comment]
maybe unrelated but since this is about dodge anim, maybe it can be helpfull

Using The ultimate dodge mod (TUDM) at the start of the setting for the commands you can dodge and the animation works, but movement cannot occur until you change between step/roll,  then PC anim works fine from the onwards, same for enemy npcs, but followers appear to try this themselves and they sometimes get stuck mid animation.

This is tested on new game with no failures on a heavily modded setup (300+ mods, well organized obviously), maybe your problem is more CGO than Nemesis related.

**Comment by DroidZed** [comment]
Dodge animation doesn't play : my character stands for about the duration of the animation.
This only happens at the first time I do the dodge , after that everything is normal.

**Comment by ShikyoKira** [comment]
what do you mean by dodge animation doesn't play? do you mean when you press the dodge key, it doesn't dodge at all?

**Comment by DroidZed** [comment]
The dodge event fires but the animation doesn't. My character stays in T pose for the period of the dodge animation then goes back to normal.
This only happens at the first time I use the dodge from CGO.

**Comment by ShikyoKira** [comment]
the Temporary t-pose is caching issue. After the first dodge, I suspect the game would cache the animation for later use again. Hence usually happen at the first time

This issue lies with CGO and your PC. I can't fix it for DServant. Thanks for the update btw

**Comment by DroidZed** [comment]
Okay I'll contact DServant and see what I find. Thanks for the explanation.
