### ISSUE TITLE
Nemesis deleting attackbehavior.hkx and then complaining it can't find it - Character behaviors ehanced

### ISSUE THREAD

**Issue by Midaychi** [ShikyoKira/Project-New-Reign---Nemesis-Main#347]
Spent a while trying to figure this out but with pre-release .84 (the latest I could find in releases), on skyrim special edition, using;
Combat Gameplay Ovheraul SE
360 movement behavior SE
Retimed Hit Frame
Character Behaviors Enhanced

the patcher would get to 99% and then error out with
```
ERROR(1210): Vital behavior file cannot be found. This will cause T-pose in game. To fix this, either reinstall the mod or manually restore this behavior file
File: c:\steam\steamapps\common\skyrim special edition\data\meshes\actors\character\behaviors\attackbehavior.hkx

Failed to generate behavior
```

At some point I ended up extracting the attackbehavior straight from combat behaviors enhanced's BSA and manually putting it into the directory, and then patching, and literally watched Nemesis delete the file around 70%, then go to 99% and complain it didn't exist.

I'm not sure what to do about it here?

**Comment by Midaychi** [comment]
The patch operation completes fine if I uncheck CBE by the way.

**Comment by Midaychi** [comment]
Just tried with the older .83 version for SSE and the patching seems to work correctly. Unfortunately the .83 version lacks a few of the other behavior mod options and the fixes you did for .84.

**Comment by ShikyoKira** [comment]
check if this file "data/meshes/actors/character/behaviors/Nemesis_AttackBehavior.xml" exists or not

**Comment by Midaychi** [comment]
Nemesis_AttackBehavior.xml exists, last modified date is ‎Tuesday, ‎August ‎7, ‎2018, ‏‎1:37:05 PM size is 2.17 MB (2,277,945 bytes)

**Comment by ShikyoKira** [comment]
then nemesis should generate attackbehavior.hkx without the need for you to extract this file out. Post your patch log here

**Comment by Midaychi** [comment]
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5048302/PatchLog.txt)

**Comment by Midaychi** [comment]
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5048311/PatchLog.txt)

**Comment by Midaychi** [comment]
I ended up removing 360 movement behavior and moving to 360 walk and run plus sse and movement behavior overhaul and for some reason now attackbehaviour compiles fine even with Character Behaviours enhanced enabled in nemesis.

The engine update was Version Code: 2574-1723
The mystery continues.
I'm guessing something in 360 movement behavior's provided patch files was silently causing nemesis to derp? I have no idea.

**Comment by Midaychi** [comment]
I was having some non-nemesis related issues with 360 walk and run plus so I re-installed everything from scratch and for some reason it all works now.. Version Code: 4964-2526, 0.84
Archery Gameplay overhaul SE w/ Author's Nemesis patch addon
Combat Gameplay overhaul
360 movement behaviour SE
Movement beahviour overhaul
Retimed Hit frame
Character behaviors enhanced

I really wish I could reproduce the issue now in a debug-gable fashion and stop wasting your time. lmao.

**Comment by ShikyoKira** [comment]
Yes, i don't blame ya. Perhaps this is the reason why some people dislike using MO2 where it fixes 1 problem but bring another?? The version code is computer generated, i don't know what it means. It is a checksum meant for syncing with other players during a Skyrim Together playthrough to avoid potential issue.

Anyway, I'm not blaming that it must be MO2's issue, but since we can't replicate this issue consistently. It hard to know where to fix. Each setup is different. Nemesis is bringing the customization to behavior, it has its own world of customization. Having 2 platforms each providing great deal of customization together, surely some will face some weird issues that are almost impossible to diagnose

To be honest, I do feel like it is wasting my time at some point specifically when dealing with issues like this that are weird and I seriously have no way to reproduce it (its not our fault btw). But I stay around for much longer than i usually would because I can tell you are trying your best to fix it, test this and that, and I respect this spirit of yours. I'm glad it turn out well in the end. Though it can be better if we can find out the reason

So.. alright, let's consider this issue settled then. If you are able to reproduce this in the future, be sure to open this issue back and provide updated info. Thanks for the report and support =)

**Comment by Slooork** [comment]
Hi!

I apologize, but I have the exact same problem.
And unfortunately I couldn't fix it by just reinstalling everything again.

Nemesis deletes the attackbehavior.hkx file and then gives error 1210 - can't find this file.

So, what information do I have:
1. I did a "clean" installation of Skyrim v 1.6.1170.0.8 + DLCs (not a license)
2. Installed the game on disk D, ini files are on disk C
3. The only mod collection I installed was Skyrim Reimagined, via Vortex, not using MO2.
https://next.nexusmods.com/skyrimspecialedition/collections/wlyq9p?tab=about
4. At the stage of working with Nemesis I get an error.

I can't identify which mod adds this animation to disable it.
In Nemesis it is labeled Character Behaviors Enhanced, but there is no such mod in Vortex so I can disable it.

If I don't "clean" this mod by Nemesis, the game doesn't start, it cusses about broken animations.

If there is a possibility - please help.
