### ISSUE TITLE
ERROR 1056

### ISSUE THREAD

**Issue by noyan11** [ShikyoKira/Project-New-Reign---Nemesis-Main#350]
after i attempted to switch nemesis from fnis i had error code 1056. I tried to look everywhere for solution but cant find it. Here is my error and patchlog
     ERROR(1056): Invalid element. Only "F" "L", or digit is acceptable as input element. Please contact the template creator
Template: b
File: #0110
Line: 23
Option: b[][B] 
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/5050973/PatchLog.txt)

**Comment by noyan11** [comment]
-UPDATE- 
Today i downloaded 0.84 beta and now im facing the issue that stucking at %99 and nothing happens. Dont know how to fix this mess.Cant get it over pls help

**Comment by DarthGamerV** [comment]
It's a common issue I believe. ShikyoKira is probably already taking a look at it, so I'm just gonna be patient since I'm a monkey regarding fixing this kind of issue myself XD. My game is working well after closing the process with it stuck at 99%. I didn't test the full extension of this yet, but basic animations and CGO is working fine, but I'm not going to proceed with my playthrough untill a proper solution is provided. Let's wait and see.

**Comment by ShikyoKira** [comment]
Old issue will not be supported. The 99% issue has been already been noted in another place. Please read the terms in the main page before posting issue, it is rude that you don't read and expect i read yours
