### ISSUE TITLE
Crash running Nemesis through MO2

### ISSUE THREAD

**Issue by CreeperLava** [ShikyoKira/Project-New-Reign---Nemesis-Main#84]
![modorganizer_2018-10-30_10-27-04](https://user-images.githubusercontent.com/12874678/47708445-61125d80-dc2e-11e8-916d-eda41f0050dd.png)

Nemesis simply crashes if run from MO2. I tried to put it in several locations (inside the mods folder and outside), with the starting directory set to my Skyrim SE folder or not. I don't see a log I could send anywhere, do tell me if there is one.

**Comment by ShikyoKira** [comment]
At what point does it crash? Is there any error message? There is a log file but only if you update/launch it thats located in nemesis_engine folder by the name `UpdateLog.txt` and `PatchLog.txt`

**Comment by CreeperLava** [comment]
It crashes at startup. I don't even see a window. I couldn't find the two text files either.

**Comment by ShikyoKira** [comment]
crash without a window. Sounds more like it isn't starting at all instead of a crash. Can you confirm it with the task manager for me? Because if it doesn't start, the problem isn't on Nemesis but MO2

**Comment by CreeperLava** [comment]
It is starting, I can confirm that. Task manager shows it.

**Comment by ShikyoKira** [comment]
Ah great, we got a better clue now. I'll tell you how Nemesis checks for your Skyrim's Data folder location, hopefully it will give u a better idea of it.

There are 2 ways it will use to look for your data directory
1. Search your registry key for it
2. Since it is expect that Nemesis will be within the data folder (Work for MO's vfs), it will use the `boost::filesystem::current_path()` and then loop `parent_path()` while match folder name for `Data` until it matches it

If it can't find data path using the registry key, it will use the 2nd method

**Comment by CreeperLava** [comment]
Okay, but that doesn't answer my question. If I start Nemesis from the Data folder, it should work as is with just one iteration of parent_path() ?

**Comment by ShikyoKira** [comment]
Well, its not meant to answer your question but rather give u the idea and perhaps we can work from there to find the cause

Wait, where do you change the starting directory? Do u mean base directory?

**Comment by CreeperLava** [comment]
![modorganizer_2018-11-05_13-36-09](https://user-images.githubusercontent.com/12874678/47998496-ca4b1280-e0ff-11e8-8377-74dbb92db720.png)

**Comment by ShikyoKira** [comment]
Thats it. It should be left empty or `E:\ModOrganizer\apps\Nemesis\Nemesis_Engine`. As for the problem of it telling u to run it from Skyrim's Data folder, I would like you to join our discord server, I'll send you a test version, `currentpath` doesn't seem to be that reliable and consistent. It got my exe path wrong by 1 letter, perhaps yours is more serious. I have changed it to using windows API in the test version, fixed my problem and it might fix yours

Here's the [link](https://discord.gg/735qdr) to our discord server

**Comment by ShikyoKira** [comment]
I'll close this as it has been fixed

**Comment by micmou** [comment]
I am sorry to post this here seeing as the thread is closed but I appear to be getting the same described issue. I have the directory to start to set as the data directory but the app just closes when I run it through MO2 although if I remove the start in parameter it complains about not being in the data directory. I would have joined the discord but the above link is no longer valid.

**Comment by SmilerVant** [comment]
Hi i was having a problem with nemesis closing when running after update for animations i fixed it by disabling  XPMSE Skeleton for RSChildren as nemesis seams to hate it, Just thought i would let everyone know

**Comment by exploiteddna** [comment]
i had this same problem.. then i realized i didnt have the nemesis mod actually active in the mods list window of MO lmao. make sure you have the mod activated, otherwise running the patcher wont do anything.. it needs those files that are located in the installed mod folder in order to run properly
